### ISSUE TITLE
LOGIN ERROR

### ISSUE THREAD

**Issue by dhifafaz** [supermemoryai/opensearch-ai#6]
I found that my self can't login into the system when using google account

Here are the error log 

```[auth][error] MissingSecret: Please define a `secret`. Read more at https://errors.authjs.dev#missingsecret
    at ..next/server/app/api/[...nextauth]/route.js:399:48444
    at iJ (..next/server/app/api/[...nextauth]/route.js:399:51038)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ..next/server/app/api/[...nextauth]/route.js:11:101046
    at async T.execute (..next/server/app/api/[...nextauth]/route.js:11:97939)
    at async T.handle (..next/server/app/api/[...nextauth]/route.js:11:102313)
    at async ea.handler (..next/server/app/api/[...nextauth]/route.js:12:20929)
    at async $ (..next/server/app/api/[...nextauth]/route.js:12:3577)
    at async runWithTaggedErrors (.node_modules/next/dist/server/web/sandbox/sandbox.js:99:24)
    at async NextNodeServer.runEdgeFunction (.node_modules/next/dist/server/next-server.js:1177:24)
[auth][error] MissingSecret: Please define a `secret`. Read more at https://errors.authjs.dev#missingsecret
    at ..next/server/app/api/[...nextauth]/route.js:399:48444
    at iJ (..next/server/app/api/[...nextauth]/route.js:399:51038)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ..next/server/app/api/[...nextauth]/route.js:11:101046
    at async T.execute (..next/server/app/api/[...nextauth]/route.js:11:97939)
    at async T.handle (..next/server/app/api/[...nextauth]/route.js:11:102313)
    at async ea.handler (..next/server/app/api/[...nextauth]/route.js:12:20929)
    at async $ (..next/server/app/api/[...nextauth]/route.js:12:3577)
    at async runWithTaggedErrors (.node_modules/next/dist/server/web/sandbox/sandbox.js:99:24)
    at async NextNodeServer.runEdgeFunction (.node_modules/next/dist/server/next-server.js:1177:24)
[auth][error] MissingSecret: Please define a `secret`. Read more at https://errors.authjs.dev#missingsecret
    at ..next/server/app/api/[...nextauth]/route.js:399:48444
    at iJ (..next/server/app/api/[...nextauth]/route.js:399:51038)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ..next/server/app/api/[...nextauth]/route.js:11:101046
    at async T.execute (..next/server/app/api/[...nextauth]/route.js:11:97939)
    at async T.handle (..next/server/app/api/[...nextauth]/route.js:11:102313)
    at async ea.handler (..next/server/app/api/[...nextauth]/route.js:12:20929)
    at async $ (..next/server/app/api/[...nextauth]/route.js:12:3577)
    at async runWithTaggedErrors (.node_modules/next/dist/server/web/sandbox/sandbox.js:99:24)
    at async NextNodeServer.runEdgeFunction (.node_modules/next/dist/server/next-server.js:1177:24)```

**Comment by MaheshtheDev** [comment]
@dhifafaz , you need to have `.env` file with 
`BACKEND_SECURITY_KEY=secretKey`

**Comment by dhifafaz** [comment]
Can i get the .env sample?

**Comment by MaheshtheDev** [comment]
@dhifafaz , `.env` file will something like this, please fill those values

``` .env
BACKEND_SECURITY_KEY="somerandomstring"
GOOGLE_CLIENT_ID=""
GOOGLE_CLIENT_SECRET=""
SEARCH_API_KEY=""
MEM0_API_KEY=""
OPENAI_API_KEY=""
```

**Comment by dhifafaz** [comment]
> @dhifafaz , `.env` file will something like this, please fill those values
> 
> ```dotenv
> BACKEND_SECURITY_KEY="somerandomstring"
> GOOGLE_CLIENT_ID=""
> GOOGLE_CLIENT_SECRET=""
> SEARCH_API_KEY=""
> MEM0_API_KEY=""
> OPENAI_API_KEY=""
> ```

Im sorry i still get the same error

`[auth][error] MissingSecret: Please define a `secret`. Read more at https://errors.authjs.dev#missingsecret
    at assertConfig (webpack-internal:///(rsc)/./node_modules/@auth/core/lib/utils/assert.js:63:16)
    at Auth (webpack-internal:///(rsc)/./node_modules/@auth/core/index.js:87:95)
[auth][error] MissingSecret: Please define a `secret`. Read more at https://errors.authjs.dev#missingsecret
    at assertConfig (webpack-internal:///(rsc)/./node_modules/@auth/core/lib/utils/assert.js:63:16)
    at Auth (webpack-internal:///(rsc)/./node_modules/@auth/core/index.js:87:95)
    at async eval (webpack-internal:///(rsc)/./node_modules/next/dist/esm/server/future/route-modules/app-route/module.js:218:37)
    at async AppRouteRouteModule.execute (webpack-internal:///(rsc)/./node_modules/next/dist/esm/server/future/route-modules/app-route/module.js:157:26)
    at async AppRouteRouteModule.handle (webpack-internal:///(rsc)/./node_modules/next/dist/esm/server/future/route-modules/app-route/module.js:280:30)
    at async EdgeRouteModuleWrapper.handler (webpack-internal:///(rsc)/./node_modules/next/dist/esm/server/web/edge-route-module-wrapper.js:92:21)
    at async adapter (webpack-internal:///(rsc)/./node_modules/next/dist/esm/server/web/adapter.js:176:16)
    at async runWithTaggedErrors (/node_modules/next/dist/server/web/sandbox/sandbox.js:99:24)
    at async DevServer.runEdgeFunction (/node_modules/next/dist/server/next-server.js:1177:24)
    at async NextNodeServer.handleCatchallRenderRequest (/node_modules/next/dist/server/next-server.js:247:37)
[auth][error] MissingSecret: Please define a `secret`. Read more at https://errors.authjs.dev#missingsecret
    at assertConfig (webpack-internal:///(rsc)/./node_modules/@auth/core/lib/utils/assert.js:63:16)
    at Auth (webpack-internal:///(rsc)/./node_modules/@auth/core/index.js:87:95)
    at async eval (webpack-internal:///(rsc)/./node_modules/next/dist/esm/server/future/route-modules/app-route/module.js:218:37)
    at async AppRouteRouteModule.execute (webpack-internal:///(rsc)/./node_modules/next/dist/esm/server/future/route-modules/app-route/module.js:157:26)
    at async AppRouteRouteModule.handle (webpack-internal:///(rsc)/./node_modules/next/dist/esm/server/future/route-modules/app-route/module.js:280:30)
    at async EdgeRouteModuleWrapper.handler (webpack-internal:///(rsc)/./node_modules/next/dist/esm/server/web/edge-route-module-wrapper.js:92:21)
    at async adapter (webpack-internal:///(rsc)/./node_modules/next/dist/esm/server/web/adapter.js:176:16)
    at async runWithTaggedErrors (/node_modules/next/dist/server/web/sandbox/sandbox.js:99:24)
    at async DevServer.runEdgeFunction (/node_modules/next/dist/server/next-server.js:1177:24)
    at async NextNodeServer.handleCatchallRenderRequest (/node_modules/next/dist/server/next-server.js:247:37)`

**Comment by MaheshtheDev** [comment]
redirect URI should be `http://localhost:3000/api/auth/callback/google`
